FEC-Wall-E/RFE-2303-FEC

client/src/App.jsx, client/src/Product.jsx, client/src/Store.jsx, client/src/index.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/QA/QA.jsx, client/src/widgets/RR/RR.jsx
all the changes we have made on liveshare
=> added all our components

client/src/App.jsx, server/helpers.js, server/index.js
=> finished routes with team on live share

client/src/Product.jsx, client/src/Store.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/RR/RR.jsx
This is where we got to by the end of the week
Passed product to each widget
=> added initial props

babel.config.js, client/src/Product.jsx, client/src/widgets/QA/QA.jsx, package-lock.json, package.json
Installed babel-jest, we should be ready to start working!
=> installed test dependencies

client/src/widgets/Outfits/Outfit.jsx
=> test commit

client/src/widgets/OV/Overview.jsx
just getting some basic info to show up
=> Added product name, product category, product price, and product description

client/src/widgets/QA/QA.jsx, client/src/widgets/QA/QA.test.js, client/src/widgets/QA/Question.jsx, client/src/widgets/QA/QuestionList.jsx, server/helpers.js
Added QuestionList component and Question component
QuestionList uses map to select 6 questions
Each of the selected questions gets passed as a prop to the Quesiton component
The Question component displays the body of the question
Added a test file, still investigating best way to actually test react components, likely will need enzyme.
=> built out questionlist component

client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx
- Add 'Your Outfit' and 'Related Products' components with basic css and structuring.
=> Add RelatedProducts and YourOutfit components with basic structuring.

client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Added a style sub-component that will the individual info and thumbnail for each style within the style selector. Also added a placeholder onclick event for the style names.
=> Style Selector Skeleton in place

client/src/widgets/QA/QA.jsx, client/src/widgets/QA/QA.test.js, client/src/widgets/QA/QuestionModal.jsx
Completed the question modal.
Prompts user to add question, name, email, all fields required.
On submit, submits post request for question and closes out modal. 
Fulfills all business requirements, still needs CSS
=> Completed question modal functionality

client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Not quite finished with the default gallery view skeleton, but I was able to add a Gallery sub-component which shows all the photos for the current product. Also moved around a few pieces of code
=> Working on Default Gallery View Skeleton

client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx
Added images, category, name, and prices to each related product. I noticed the first related product did not have an image associated with it, so I added a placeholder image for that product.
=> Added images, category, name, and prices to each related product

client/src/widgets/QA/QA.test.js, client/src/widgets/QA/QuestionModal.jsx
Added test specifically for Q&A, still trying to learn React Testing Library
=> added example test for question modal

client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx, client/src/widgets/Outfits/YourOutfitsEntry.jsx, package.json
- Added on click event for "YourOutfits" component so that it will save current product to local storage.
- Added image, category, name, and price for said item added
=> Added localStorage for "Your Outfits" component

client/src/widgets/QA/Answer.jsx, client/src/widgets/QA/AnswerList.jsx, client/src/widgets/QA/QA.jsx, client/src/widgets/QA/Question.jsx
Created AnswerList and Answer components
For each question, pass the answers to AnswerList
AnswerList uses map and passes each answer to Answer component
Answer displays the answer, asker, date and appropriate buttons (mark helpful, report).
=> created basic answer component

client/src/Product.jsx, client/src/widgets/RR/RR.jsx, client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx, package-lock.json, package.json, server/helpers.js
The more reviews button is working and showing 2 more reviews at a time. After 150px the div becomes scrollable. For now I just have the review body showing and am going to work on the tile details.
=> More Reviews button and Review Tile rendering

client/src/widgets/OV/ExtendedGallery.jsx, client/src/widgets/OV/Gallery.jsx
Added a Extended Gallery sub-component and a button that shows it when pressed. Also added a bit of inline css in an attempt to not take up so much space with my gallery photos.
=> Added Extended Gallery Skeleton

client/src/widgets/OV/ExtendedGallery.jsx, client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/GalleryPhoto.jsx
Made each photo its own component, and edited some inline css to make things a bit prettier till we can focus on css down the road.
=> Default gallery view fix

client/src/Product.jsx, client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx, package-lock.json, package.json, server/helpers.js, server/index.js
I installed the npm package for the stars and they are showing up correctly for each review tile. I also changed the API request so I will be able to set the sort type from the react component. I will need this when working on the sort dropdown.
=> Stars added and working, sortType added to API calls

client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx, client/src/widgets/RR/Sort.jsx, server/helpers.js
I had to change the function in helper to show 200+ results for it to accurately show the newest. Made some changes to the review tile, but need to work on the specificities more. The sort dropdown is working and updating the review list accordingly.
=> Review tile work and Sort functionality

client/src/widgets/RR/NewReview.jsx, client/src/widgets/RR/ReviewsList.jsx
Able to toggle modal, but it is not posting to database yet
=> NewReview Modal added and basic structure created

client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/GalleryPhoto.jsx, client/src/widgets/OV/MainGalleryPhoto.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Added some logic for the gallery when it comes to setting the inital main photo, also made it so that the user can select pic and have that one be the 'main pic'. Also been playing with flexbox a bit, added some inline to make things a bit prettier in the meantime
=> Added some gallery logic

client/src/widgets/QA/Answer.jsx, client/src/widgets/QA/AnswerModal.jsx, client/src/widgets/QA/PhotoModal.jsx, client/src/widgets/QA/QA.jsx, client/src/widgets/QA/Question.jsx, client/src/widgets/QA/QuestionList.jsx
The important changes are in QA.jsx, Question.jsx and QuestionList.jsx - I added a function to mark questions as helpful, everything with that works as expected and fulfills the business docs.
There are changes to the Answer modal and Photo modal - some bugs I am figuring out with the photo modal. 
These changes can effectively be ignored for now.
The user can still upload answers, but any photos added right now won't work. 
Adding the photos might not be part of the core business docs, it's unclear.
=> can mark questions as helpful. fixing bug in photo upload

client/src/widgets/OV/ExtendedGallery.jsx, client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Photos/MainGalleryPhoto.jsx, client/src/widgets/OV/ProductInfo.jsx
just a few QOL changes, also added functionality for main pic, when clicked it will open the extended view
=> QOL changes

client/src/widgets/Outfits/CompareModal.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx
1. Added comparison modal box to center of screen
2. Added button to close modal
=> Added comparison modal box to center of screen

client/src/widgets/QA/AnswerModal.jsx, client/src/widgets/QA/PhotoModal.jsx
Changed the photo modal and answer modal so that user uploaded thumbnails display in answer modal
When making a post request for a new answer, sends a placeholder image instead of user uploaded images.
Now answer modal and photo modal meet business requirements
=> fixed photo modal

client/src/widgets/QA/Answer.jsx, client/src/widgets/QA/Question.jsx
Can report an answer. The component will change to reflect this and on the next refresh the answer will not appear.
=> answer reporting works

client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Photos/GalleryPhoto.jsx, client/src/widgets/OV/Photos/MainGalleryPhoto.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx, client/src/widgets/OV/Tests/ProductInfo.test.js
Added in some more css, also added functionality for changing the selected gallery item, you should now be able to see other items appear in the gallery when they are clicked in the 'related products'.
=> Default gallery view

client/src/widgets/QA/Answer.jsx, client/src/widgets/QA/QuestionList.jsx
If there are more than 4 answered questions, there is a button "view more questions" that will display the rest of the questions in a scrollable list
=> can expand question list and collapse it

client/src/widgets/RR/Characteristics.jsx, client/src/widgets/RR/NewReview.jsx
The characteristics section was super challenging for me. I ended up making a new component for it because it had a lot going on but I think I finally figured it out. Still need to work on making the summary, body, name, email, and photos working. This one has a lot going on!
=> More work on add review component

client/src/widgets/Outfits/CompareModal.jsx, client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx
1. Added characteristics for both current and related product
2. Added values for current product characteristics
3. Added values for related product characteristics
4. Still need to bug fix names (currently both current and related product display current product name)
=> Added characteristics for current product and old product

client/src/widgets/QA/QA.test.js, client/src/widgets/QA/Question.jsx, client/src/widgets/QA/QuestionList.jsx, client/src/widgets/QA/QuestionSearch.jsx
I commented out my current test for QuestionList as it was outdated and not working.
I fixed the search bar so now it properly displays the rest of the filtered question and not just the question body. 
I moved some logic into useEffect blocks so that the filtered questions will properly render their information.
=> fixed search bug, works now

client/src/widgets/OV/AddToCart.jsx, client/src/widgets/OV/Overview.jsx
Yeeesh, this took me wayy longer than I thought it would, and it looks pretty messy haha, but the functionality for the size selector and quantity selector is complete. It should reflect the correct sizes and the corresponding available quantities.
=> Size selector and Quantity selector functionality complete

client/src/widgets/RR/Characteristics.jsx, client/src/widgets/RR/NewReview.jsx
Able to post reviews to the DB, I haven't made the add photos functional yet. I want to work on my other tickets before tomorrow's progress demo so my whole widget looks more complete. Right now for the photos I am sending an array with random strings (the same for each review)
=> Adding Review Mostly Complete

client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx, client/src/widgets/Outfits/YourOutfitsEntry.jsx
1. Added delete button for 'YourOutfits' component. Still buggy. Wanted to make a progress save.
2. Changed placeholder image for sold out item.
=> Added delete button for Outfits component and changed placeholder image

client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Photos/MainGalleryPhoto.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Added some css to style selector, also fixed bug in gallery. Previously, if a thumbnail was clicked then the product was changed, the main photo wouldn't update to the new product, this has been fixed.
=> Style selector + gallery bug fix

client/src/widgets/QA/PhotoModal.jsx, client/src/widgets/QA/PhotoModal.test.js, client/src/widgets/QA/QA.jsx, client/src/widgets/QA/QA.test.js, client/src/widgets/QA/Question.jsx, client/src/widgets/QA/QuestionList.jsx, client/src/widgets/QA/QuestionSearch.jsx, package-lock.json, package.json
I also installed a new dependency for one of my tests, just a heads up
=> added tests for photo modal, minor css changes

client/src/widgets/RR/PhotoModal.jsx, client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx, client/src/widgets/RR/Sort.jsx
I added more styling to the review tile and added a new file for the photo modal as it was taking up a lot of space in my review tile code (that is already a bit messy). The tile itself is now meeting the business requirements though!
=> Review Tile Business Requirements Met

client/src/widgets/OV/AddToCart.jsx, client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Thought I was almost done earlier haha, guess not. Added some functionality to styles so when clicked, they reflect the different quantities available. Just need to make the size selector default to an empty selection whenever a style is clicked, and it should be done then.
=> Style selector and Quantity selector nearly done

client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx
1. Completed formatting for carousel
2. Added working buttons to carousel
3. Carousel very buggy
4. Inline css is very repetitive, could have used a css file here for sure
=> Added working buttons to carousel. Carousel buggy

client/src/widgets/RR/NewReview.jsx, client/src/widgets/RR/PhotoModal.jsx, client/src/widgets/RR/RR.jsx, client/src/widgets/RR/RatingBreakdown.jsx, client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx
The review breakdown is now working and changes when another product is selected. I added the current product in useEffect of the review list as well because I noticed that wasn't changing. I fixed some other bugs too
=> Review Breakdown Complete, other minor changes made

client/src/widgets/QA/Answer.jsx
Each review photo zooms in on click.
Going to work on the CSS for my question and answer modals, then I will make this a modal as well.
=> review photos zoom in on click

client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/ProductInfo.jsx
Added sale price to product info, and added average rating for the current product
=> Product info additions

client/src/widgets/QA/AnswerModal.jsx, client/src/widgets/QA/PhotoModal.jsx, client/src/widgets/QA/QuestionModal.jsx
No logic was changed, but now the QA modals should look a bit better. Still work to be done on the QA modal CSS.
=> changed css for question, answer and QA photo modals

client/src/Product.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/ProductInfo.jsx, server/helpers.js
Added a 'next product' button which will cycle through 15 products, adding this made me need to do some bug fixing in how I handle styles and the star reviews.
=> Small additions

client/src/widgets/RR/ProductBreakdown.jsx, client/src/widgets/RR/RatingBreakdown.jsx
Product breakdown is now meeting all business requirements. I also edited the console.logs from the rating breakdown
=> Product breakdown complete

client/src/widgets/OV/AddToCart.jsx
Added logic for style selector so that the size is set to 'select size' every time the product or style changes, also added an 'out of stock' option. Also greyed out the add to cart button unless a size is selected.
=> Fixed style selector and quantity selector

client/src/widgets/Outfits/CompareModal.jsx, client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx, client/src/widgets/Outfits/YourOutfitsEntry.jsx
1. Added stars to component (basically used Koen's code🤣)
2. Small QOL changes
=> Added stars to components

client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Added checkmark and green border to the style which is currently selected, it will also automatically default to the first style when initially loading or picking a new product.
=> added a checkmark and border

client/src/widgets/RR/ProductBreakdown.jsx, client/src/widgets/RR/RatingBreakdown.jsx
With Koen's help my stars are now able to be partially filled! The rating breakdown is officially meeting business requirements
=> Edits to Product Breakdown and Rating Breakdown

client/src/widgets/OV/AddToCart.jsx, client/src/widgets/OV/Overview.jsx
Add to cart will now send that info to the API and add it to the cart. Also fixed a bug that caused the size selector to lose its spot when initially used.
=> Implemented Add to Cart + bug fix

client/src/widgets/Outfits/CompareModal.jsx, client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx
1. Fixed carousels to show next item on button click. Down side is it only shows one product at a time🙃. One bug fix at a time I guess haha.
=> Got carousel to show 1 product and button to show next product

client/src/widgets/RR/AddPhoto.jsx, client/src/widgets/RR/NewReview.jsx
Dan's code helped a lot! I ended up having to do it slightly differently with how I was sharing states. The thumbnails for the photos are appearing(and you can only add 5 photos), but the same photo is getting posted each time (like the boxes). I'm thinking of making an array of 5 random url photos for it to go through for the main demo.
=> Add photo working now! 

client/src/Product.jsx, client/src/widgets/Outfits/CompareModal.jsx, client/src/widgets/Outfits/Outfit.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx, client/src/widgets/Outfits/YourOutfitsEntry.jsx
1. Carousel now displays 3 items.
2. Buttons work properly to display 1 new item on click
3. Left Button does not appear when page loads, and right button does not display when you reach last item on carousel
4. Still need to fix a bug in caparison modal and format carousels to change size based on screen size
=> Successfully got carousel working properly

client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx
1. Fixed got comparison modal to display correct items values
=> Fixed got comparision modal working as intended

client/src/widgets/QA/QA.test.js
In my QA test file I was able to replace an axios get request with a mock function that returns an object I set in the test.
=> successfully stubbed axios get request in test

client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/GalleryCarousel.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Photos/GalleryPhoto.jsx, client/src/widgets/OV/Photos/MainGalleryPhoto.jsx
Added in buttons and logic for saving the index of the current image selected. Also did a lot of css fixes, I moved quite a bit of stuff to my css file, so I have kind of a weird split of in-line and in-file css,  will consolidate later
=> default gallery view meets business doc reqs

.gitignore, client/dist/OVstyles.css, client/src/widgets/OV/AddToCart.jsx, client/src/widgets/OV/ExtendedGallery.jsx, client/src/widgets/OV/ExtendedGalleryCarousel.jsx, client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/GalleryCarousel.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/Photos/ExtendedGalleryPhoto.jsx, client/src/widgets/OV/Photos/ExtendedViewMainPhoto.jsx, client/src/widgets/OV/Photos/MainGalleryPhoto.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/Style.jsx, client/src/widgets/OV/StyleSelector.jsx
Apologies in advance for whoever has to review this. Added quite a bit, full functionality for extended view is nearly there, only missing one requirement. Also converted basically all my inline css to file.
=> Extended gallery view nearly done

client/src/widgets/QA/AnswerModal.test.js, client/src/widgets/QA/QuestionList.test.js
Figured out how to mock API calls in tests
This is a big commit but it is mostly setting up practice data.
=> added tests

client/dist/styles.css, client/src/widgets/RR/Characteristics.jsx, client/src/widgets/RR/RR.test.js, client/src/widgets/RR/RatingBreakdown.jsx, client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/Sort.jsx, package-lock.json, package.json
I'm not sure why the dependency changed, I hope it doesn't mess everyone's up we will see
=> testing is now almost at 70%

client/src/widgets/OV/AddToCart.jsx, client/src/widgets/OV/ExtendedGallery.jsx, client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/Overview.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/StyleSelector.jsx, client/src/widgets/OV/Tests/AddToCart.test.js, client/src/widgets/OV/Tests/EntendedGallery.test.js, client/src/widgets/OV/Tests/Gallery.test.js, client/src/widgets/OV/Tests/Overview.test.js, client/src/widgets/OV/Tests/StyleSelector.test.js
Have some very basic tests that get me to 40% total, like 90% of the added code is example data.
=> Testing at 40%

client/src/widgets/QA/Answer.jsx, client/src/widgets/QA/AnswerList.jsx, client/src/widgets/QA/AnswerModal.jsx, client/src/widgets/QA/AnswerModal.test.js, client/src/widgets/QA/AnswerPhotoModal.jsx, client/src/widgets/QA/PhotoModal.jsx, client/src/widgets/QA/QA.jsx, client/src/widgets/QA/QA.test.js, client/src/widgets/QA/Question.jsx, client/src/widgets/QA/QuestionList.jsx, client/src/widgets/QA/QuestionModal.jsx, client/src/widgets/QA/QuestionSearch.jsx
No changes to logic - it is pretty much all CSS, I know it looks like a lot! 
I did add a few tests, but still can't test out the form submission which is keeping my coverage at about 60%. Most of the changes in my tests are me commenting out tests which I can't get working yet.
=> CSS changes

client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx
The business requirements says to mark the user as verified if they have made a sale, but I confirmed with Claire there is no way to do this. Right now the checkmark will appear if the user had previously made a review and she said it was fine to leave it this way.
=> Checkmark appears for verified user

client/src/widgets/Outfits/RelatedProductsCarousel.test.js, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/RelatedProductsEntry.test.js, client/src/widgets/Outfits/YourOutfitsEntry.jsx, client/src/widgets/Outfits/YourOutfitsEntry.test.js
1. Updated test for relatedProductsCarousel
2. Changed css for products on sale
=> Small css changes and test changes

client/src/widgets/RR/RR.test.js, client/src/widgets/RR/ReviewTile.jsx
I had to make edits to my tests because I passed an additional prop to the review tile. They are all passing now!
=> Able to report a review 

client/dist/OVstyles.css, client/src/Store.jsx, client/src/index.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfitsEntry.jsx, client/src/widgets/RR/RR.jsx
Added a semi-functional light dark mode button
=> Added a semi-functional light dark mode button

client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/PostAPIInteraction.jsx, server/helpers.js, server/index.js
=> Added interaction API

client/src/widgets/RR/Characteristics.jsx, client/src/widgets/RR/NewReview.jsx, client/src/widgets/RR/ProductBreakdown.jsx, client/src/widgets/RR/RR.jsx, client/src/widgets/RR/RatingBreakdown.jsx, client/src/widgets/RR/ReviewTile.jsx, client/src/widgets/RR/ReviewsList.jsx, client/src/widgets/RR/Sort.jsx
close button added to new review modal, percentage of recommended review displayed, more review button now disappears when all reviews appear in the list.
=> Even more CSS changes and also added more functionality

client/dist/OVstyles.css, client/src/widgets/OV/Photos/ExtendedGalleryPhoto.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/Style.jsx
fixed bug for star ratings that caused the stars to show the wrong rating
=> small css changes + ratings bug fix

client/src/widgets/Outfits/CompareModal.jsx, client/src/widgets/Outfits/RelatedProductsCarousel.jsx, client/src/widgets/Outfits/RelatedProductsEntry.jsx, client/src/widgets/Outfits/YourOutfits.jsx, client/src/widgets/Outfits/YourOutfitsEntry.jsx
1. added interaction API to all clickable buttons in Outfit widget
2. Fixed bug with stars displaying wrong amount
=> added interaction API to all clickable buttons in Outfit widget

client/dist/OVstyles.css, client/src/Store.jsx, client/src/widgets/OV/ExtendedGallery.jsx, client/src/widgets/OV/Gallery.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/StyleSelector.jsx
A few css changes, along with the addition of the interaction api to my onClicks, and I also added a review count to the read all reviews button.
=> lot of small changes, added review count to 'read all reviews' btn

.gitignore, client/dist/index.html
Removed index.html from gitignore
=> Removed index.html from gitignore

client/src/App.jsx, client/src/Product.jsx, client/src/widgets/Outfits/Outfit.jsx
changed font family and removed commented-out code
=> changed font family and removed commented-out code

client/dist/index.html
=> Changed Browser title

client/src/Store.jsx
Adding additional text to main page
=> Adding additional text to main page

client/dist/OVstyles.css, client/src/Product.jsx, client/src/Store.jsx, client/src/widgets/OV/ProductInfo.jsx, client/src/widgets/OV/Style.jsx
next product button will now cycle between 3 specific products, we can change these if necessary later
=> Changed logic of next product Btn and added some css

client/src/Store.jsx
=> moved header
